/* Auto-generated by gen-data.js at 2025-08-31T16:24:01.026Z */
export const CITY_META = {
  "Toya": {
    "en": "Toya",
    "zh": "洞爺湖"
  },
  "Otaru": {
    "en": "Otaru",
    "zh": "小樽"
  },
  "Sapporo": {
    "en": "Sapporo",
    "zh": "札幌"
  }
};

export const toyaSpots = [
  {
    "id": "lake-toya-nakajima",
    "nameEn": "Nakajima Island, Lake Toya",
    "nameZh": "洞爺湖中島",
    "tags": [
      "lake",
      "island",
      "nature"
    ],
    "rating": 4.4,
    "blurb": "位於洞爺湖中央的島嶼，可搭乘遊船登島健行。",
    "order": 10,
    "images": [
      "images/Toya/洞爺湖中島/1.jpeg",
      "images/Toya/洞爺湖中島/2.jpeg",
      "images/Toya/洞爺湖中島/3.jpeg",
      "images/Toya/洞爺湖中島/4.jpeg",
      "images/Toya/洞爺湖中島/5.jpeg",
      "images/Toya/洞爺湖中島/6.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Lake+Toya+Nakajima"
  },
  {
    "id": "toya-manseikaku-onsen",
    "nameEn": "Toya Manseikaku Onsen Hotel",
    "nameZh": "洞爺湖萬世閣溫泉飯店",
    "tags": [
      "hotel",
      "onsen",
      "spa"
    ],
    "rating": 4.3,
    "blurb": "洞爺湖畔著名的溫泉飯店，也提供日歸泡湯。",
    "order": 20,
    "images": [
      "images/Toya/萬世閣日歸溫泉/1.jpeg",
      "images/Toya/萬世閣日歸溫泉/2.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Toya+Manseikaku+Hotel"
  },
  {
    "id": "lake-toya-fireworks",
    "nameEn": "Lake Toya Long-run Fireworks Festival",
    "nameZh": "洞爺湖長期煙火大會",
    "tags": [
      "festival",
      "fireworks",
      "night"
    ],
    "rating": 4.7,
    "blurb": "每年4月至10月舉行的長期煙火表演，湖面上綻放絢爛煙火。",
    "order": 30,
    "images": [
      "images/Toya/洞爺湖煙火/IMG_2921.jpeg",
      "images/Toya/洞爺湖煙火/IMG_2923.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Lake+Toya+Fireworks"
  },
  {
    "id": "noboribetsu-jigokudani",
    "nameEn": "Noboribetsu Jigokudani (Hell Valley)",
    "nameZh": "登別地獄谷",
    "tags": [
      "volcano",
      "hot-spring",
      "valley"
    ],
    "rating": 4.6,
    "blurb": "硫磺煙霧瀰漫的火山地形，登別溫泉的象徵景點。",
    "order": 30,
    "images": [
      "images/Toya/登別地獄谷/IMG_2806.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Noboribetsu+Jigokudani"
  },
  {
    "id": "mt-usu",
    "nameEn": "Mt. Usu",
    "nameZh": "有珠山",
    "tags": [
      "mountain",
      "volcano",
      "view"
    ],
    "rating": 4.5,
    "blurb": "活火山景點，可搭乘有珠山纜車俯瞰洞爺湖與昭和新山。",
    "order": 40,
    "images": [
      "images/Toya/有珠山/1.jpeg",
      "images/Toya/有珠山/2.jpeg",
      "images/Toya/有珠山/3.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Mt.+Usu"
  },
  {
    "id": "mt-yotei",
    "nameEn": "Mt. Yotei",
    "nameZh": "羊蹄山",
    "tags": [
      "mountain",
      "hiking",
      "view"
    ],
    "rating": 4.7,
    "blurb": "有北海道富士之稱的名山，山形優美，是登山健行與攝影聖地。",
    "order": 40,
    "images": [
      "images/Toya/羊蹄山/1.jpeg",
      "images/Toya/羊蹄山/2.jpeg",
      "images/Toya/羊蹄山/3.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Mt.+Yotei"
  },
  {
    "id": "makkari-riverside-park",
    "nameEn": "Makkari Riverside Park",
    "nameZh": "真狩川公園",
    "tags": [
      "park",
      "nature",
      "view"
    ],
    "rating": 4.2,
    "blurb": "真狩村的小公園，可以欣賞羊蹄山的全景。",
    "order": 60,
    "images": [
      "images/Toya/真狩村公園/1.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Makkari+Riverside+Park"
  },
  {
    "id": "toya-onsen-7-11",
    "nameEn": "7-Eleven Toyako Onsen",
    "nameZh": "洞爺湖溫泉街7-11",
    "tags": [
      "convenience-store",
      "town"
    ],
    "rating": 3.8,
    "blurb": "洞爺湖溫泉街上的便利商店，以黑白灰色系招牌聞名，是少數特例的 7-11。",
    "order": 80,
    "images": [
      "images/Toya/洞爺湖灰階7-11/IMG_2811.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=7-Eleven+Toyako+Onsen"
  }
];
export const otaruSpots = [
  {
    "id": "otaru-canal",
    "nameEn": "Otaru Canal",
    "nameZh": "小樽運河",
    "tags": [
      "canal",
      "landmark",
      "scenery"
    ],
    "rating": 5,
    "blurb": "小樽最具代表性的景點，沿岸有倉庫群與散步道，夜晚景色浪漫。",
    "order": 1,
    "images": [
      "images/Otaru/小樽運河/1.jpeg",
      "images/Otaru/小樽運河/2.jpeg",
      "images/Otaru/小樽運河/3.jpeg",
      "images/Otaru/小樽運河/4.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Otaru+Canal"
  },
  {
    "id": "debuku-alley",
    "nameEn": "Debuku Alley",
    "nameZh": "出拔小路",
    "tags": [
      "alley",
      "shopping",
      "street"
    ],
    "rating": 4,
    "blurb": "小樽的特色小路，聚集許多餐廳與小店，適合散步與覓食。",
    "order": 2,
    "images": [
      "images/Otaru/出拔小路/1.jpeg",
      "images/Otaru/出拔小路/2.jpeg",
      "images/Otaru/出拔小路/3.jpeg"
    ],
    "address": "小樽市色內1丁目",
    "mapUrl": "https://maps.google.com/?q=Otaru+Debuku+Alley"
  },
  {
    "id": "blue-cave",
    "nameEn": "Blue Cave",
    "nameZh": "青之洞窟",
    "tags": [
      "cruise",
      "nature",
      "sea"
    ],
    "rating": 4.9,
    "blurb": "搭船遊覽小樽海岸的秘境景點，海水呈現夢幻藍色光影。",
    "order": 3,
    "images": [
      "images/Otaru/青之洞窟/IMG_3064.jpeg",
      "images/Otaru/青之洞窟/IMG_3068.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Otaru+Blue+Cave"
  },
  {
    "id": "kitaichi-glass",
    "nameEn": "Kitaichi Glass",
    "nameZh": "北一硝子",
    "tags": [
      "glassware",
      "museum",
      "shopping"
    ],
    "rating": 3.5,
    "blurb": "知名的玻璃工藝品牌，展示販售精美玻璃製品，也有體驗工坊。",
    "order": 4,
    "images": [
      "images/Otaru/北一硝子/IMG_3105.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Kitaichi+Glass+Otaru"
  }
];
export const sapporoSpots = [
  {
    "id": "shiroi-koibito-park",
    "nameEn": "Shiroi Koibito Park",
    "nameZh": "白色戀人工廠",
    "tags": [
      "museum",
      "park",
      "sweets"
    ],
    "rating": 4.5,
    "blurb": "知名白色戀人餅乾的主題園區與工廠，結合觀光與購物。",
    "order": 10,
    "images": [
      "images/Sapporo/白色戀人工廠/1.jpeg",
      "images/Sapporo/白色戀人工廠/2.jpeg",
      "images/Sapporo/白色戀人工廠/3.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Shiroi+Koibito+Park"
  },
  {
    "id": "sapporo-tv-tower",
    "nameEn": "Sapporo TV Tower",
    "nameZh": "札幌電視塔",
    "tags": [
      "landmark",
      "tower",
      "nightview"
    ],
    "rating": 4.3,
    "blurb": "位於大通公園東端的電視塔，可俯瞰札幌市區景色。",
    "order": 20,
    "images": [
      "images/Sapporo/札幌電視塔/IMG_3272.jpeg",
      "images/Sapporo/札幌電視塔/IMG_3304 2.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Sapporo+TV+Tower"
  },
  {
    "id": "maruyama-zoo",
    "nameEn": "Maruyama Zoo",
    "nameZh": "円山動物園",
    "tags": [
      "zoo",
      "family",
      "animals"
    ],
    "rating": 4.2,
    "blurb": "札幌市立動物園，擁有北極熊等寒帶動物，適合親子同遊。",
    "order": 30,
    "images": [
      "images/Sapporo/円山動物園/IMG_3188.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Maruyama+Zoo"
  },
  {
    "id": "tanukikoji-shopping-street",
    "nameEn": "Tanukikoji Shopping Street",
    "nameZh": "狸小路商店街",
    "tags": [
      "shopping",
      "street",
      "food"
    ],
    "rating": 4.3,
    "blurb": "札幌最熱鬧的商店街之一，全長約1公里，聚集各式餐廳、伴手禮與藥妝店，觀光客必訪。",
    "order": 30,
    "images": [
      "images/Sapporo/狸小路商店街/IMG_3178.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/DBbo4zxDjzwmvDrJ9"
  },
  {
    "id": "hokkaido-shrine",
    "nameEn": "Hokkaido Shrine",
    "nameZh": "北海道神宮",
    "tags": [
      "shrine",
      "culture",
      "nature"
    ],
    "rating": 4.6,
    "blurb": "札幌市內的重要神社，櫻花與梅花季節尤為熱鬧。",
    "order": 40,
    "images": [
      "images/Sapporo/北海道神宮/1.jpeg",
      "images/Sapporo/北海道神宮/2.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Hokkaido+Shrine"
  },
  {
    "id": "sapporo-clock-tower",
    "nameEn": "Sapporo Clock Tower",
    "nameZh": "札幌時計台",
    "tags": [
      "landmark",
      "history",
      "architecture"
    ],
    "rating": 4,
    "blurb": "札幌地標之一，歷史悠久的木造鐘樓建築。",
    "order": 50,
    "images": [
      "images/Sapporo/札幌時計台/IMG_3256.jpeg",
      "images/Sapporo/札幌時計台/IMG_3263.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Sapporo+Clock+Tower"
  }
];

export const foodItems = [
  {
    "id": "ichiran-ramen",
    "title": "一蘭拉麵",
    "note": "來日本一定要踩點的拉麵。",
    "rating": 4,
    "tags": [
      "ramen",
      "tonkotsu"
    ],
    "images": [
      "images/food/一蘭拉麵/IMG_3203.jpeg"
    ],
    "mapUrl": "https://maps.google.com/?q=Ichiran+Sapporo"
  },
  {
    "id": "sankaku-uni-don",
    "title": "三角市場海膽丼 味処たけだ",
    "note": "小樽三角市場的海膽丼，海膽普普通通。",
    "rating": 3.6,
    "tags": [
      "seafood",
      "donburi",
      "uni"
    ],
    "images": [
      "images/food/三角市場海膽丼(Ajidokoro Takeda)/1.jpeg",
      "images/food/三角市場海膽丼(Ajidokoro Takeda)/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/FbTiCRS67BsR1hD88"
  },
  {
    "id": "sapporo-ebi-mensha-tsukemen",
    "title": "札幌海老麺舎 沾麵",
    "note": "主打濃郁蝦味湯頭的沾麵，香氣十足。",
    "rating": 4.3,
    "tags": [
      "tsukemen",
      "ramen",
      "shrimp"
    ],
    "images": [
      "images/food/札幌海老麺舎 沾麵/IMG_3161.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/BzxccMnDYeoeYZ2K6"
  },
  {
    "id": "popsicle",
    "title": "冰棒",
    "note": "肚子一有空檔一定要來上一支！",
    "rating": 4.5,
    "tags": [
      "dessert",
      "ice-cream"
    ],
    "images": [
      "images/food/冰棒/IMG_2812.jpeg",
      "images/food/冰棒/IMG_2928.jpeg",
      "images/food/冰棒/IMG_3018.jpeg",
      "images/food/冰棒/IMG_3126.jpeg",
      "images/food/冰棒/IMG_3182.jpeg",
      "images/food/冰棒/IMG_3183.jpeg"
    ],
    "mapUrl": ""
  },
  {
    "id": "katsuissen-conveyor-sushi",
    "title": "回転すし 活一鮮",
    "note": "迴轉壽司，食材新鮮、選擇多樣。",
    "rating": 3.9,
    "tags": [
      "sushi",
      "conveyor-sushi",
      "seafood"
    ],
    "images": [
      "images/food/回転すし 活一鮮/1.jpeg",
      "images/food/回転すし 活一鮮/IMG_3205.jpeg",
      "images/food/回転すし 活一鮮/IMG_3207.jpeg",
      "images/food/回転すし 活一鮮/IMG_3208.jpeg",
      "images/food/回転すし 活一鮮/IMG_3209.jpeg",
      "images/food/回転すし 活一鮮/IMG_3210.jpeg",
      "images/food/回転すし 活一鮮/IMG_3211.jpeg",
      "images/food/回転すし 活一鮮/IMG_3212.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/pWpVL9prDQFA4nie6"
  },
  {
    "id": "jingisukan-bbq",
    "title": "成吉思汗烤肉",
    "note": "北海道經典烤羊肉料理，使用特製鐵鍋現烤。",
    "rating": 3.2,
    "tags": [
      "jingisukan",
      "bbq",
      "lamb"
    ],
    "images": [
      "images/food/陳吉思汗烤肉/1.jpeg",
      "images/food/陳吉思汗烤肉/2.jpeg",
      "images/food/陳吉思汗烤肉/3.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/aT49FULZuzS4YdNd8"
  },
  {
    "id": "toya-manseikaku-ramen",
    "title": "旬彩和房 居酒屋",
    "note": "萬世閣酒店的宵夜拉麵，晚上少數的選擇。",
    "rating": 3.8,
    "tags": [
      "ramen",
      "hotel"
    ],
    "images": [
      "images/food/洞爺湖萬世閣酒店拉麵/1.jpeg",
      "images/food/洞爺湖萬世閣酒店拉麵/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/GmSPZ3ttn96o9U958"
  },
  {
    "id": "hyoe-udon",
    "title": "兵衛烏龍麵 + 水菜",
    "note": "烏龍麵+水菜完美的搭配。",
    "rating": 4.2,
    "tags": [
      "udon"
    ],
    "images": [
      "images/food/兵衛烏龍麵+水菜/1.jpeg",
      "images/food/兵衛烏龍麵+水菜/2.jpeg"
    ],
    "mapUrl": ""
  },
  {
    "id": "convenience-store-supermarket",
    "title": "便利商店與超市",
    "note": "當地超市&便利商店美味的食物。",
    "rating": 4.2,
    "tags": [
      "convenience-store",
      "supermarket"
    ],
    "images": [
      "images/food/便利商店&超市/1.jpeg",
      "images/food/便利商店&超市/2.jpeg",
      "images/food/便利商店&超市/3.jpeg",
      "images/food/便利商店&超市/4.jpeg",
      "images/food/便利商店&超市/5.jpeg",
      "images/food/便利商店&超市/6.jpeg",
      "images/food/便利商店&超市/IMG_2814.jpeg",
      "images/food/便利商店&超市/IMG_2929.jpeg"
    ],
    "mapUrl": ""
  },
  {
    "id": "jingu-chaya-ice-cream",
    "title": "神宮茶屋冰淇淋",
    "note": "北海道神宮旁的人氣冰淇淋，奶香濃郁。",
    "rating": 5,
    "tags": [
      "dessert",
      "ice-cream"
    ],
    "images": [
      "images/food/神宮茶屋冰淇淋/IMG_3202.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/oSLXvYWRYcJ6eTrf6"
  },
  {
    "id": "snow-brand-ice-cream",
    "title": "雪印冰淇淋",
    "note": "雪印品牌的霜淇淋，奶味濃厚。",
    "rating": 4,
    "tags": [
      "dessert",
      "ice-cream"
    ],
    "images": [
      "images/food/雪印冰淇淋/IMG_3255.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/CQS6FmhH9VmqLvsw9"
  },
  {
    "id": "okushiba-shoten-soup-curry",
    "title": "奥芝商店 湯咖哩",
    "note": "札幌名店的湯咖哩，香料濃郁、蔬菜豐富。",
    "rating": 4.5,
    "tags": [
      "soup-curry",
      "sapporo"
    ],
    "images": [
      "images/food/奥芝商店湯咖哩/IMG_3240.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/pJFRrByNRJNDGvrR7"
  },
  {
    "id": "supermarket-seafood",
    "title": "超市海鮮",
    "note": "在超市買到的新鮮海鮮，平價又好吃！",
    "rating": 4.8,
    "tags": [
      "seafood",
      "supermarket",
      "takeout"
    ],
    "images": [
      "images/food/超市海鮮/1.jpeg",
      "images/food/超市海鮮/2.jpeg",
      "images/food/超市海鮮/3.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/EtiBCNk4Hh7jfc9S8"
  },
  {
    "id": "black-thunder",
    "title": "雷神巧克力",
    "note": "來日本必吃的巧克力！",
    "rating": 4.3,
    "tags": [
      "snack",
      "chocolate"
    ],
    "images": [
      "images/food/雷神/1.jpeg",
      "images/food/雷神/2.jpeg"
    ],
    "mapUrl": ""
  },
  {
    "id": "masuda-udon",
    "title": "増田うどん",
    "note": "湯頭清爽的手工烏龍麵。",
    "rating": 4.4,
    "tags": [
      "udon",
      "noodles"
    ],
    "images": [
      "images/food/Masuda udon/IMG_3177.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/Cx9ufpWp75acfFxg7"
  },
  {
    "id": "gyoza-factory",
    "title": "餃子製造所",
    "note": "現煎的日式餃子，外皮香脆、內餡多汁，炸雞更好吃。",
    "rating": 4.1,
    "tags": [
      "gyoza",
      "dumplings"
    ],
    "images": [
      "images/food/餃子製造所/1.jpeg",
      "images/food/餃子製造所/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/1rsfUxXquLyp8EndA"
  },
  {
    "id": "airport-donburi",
    "title": "機場丼飯",
    "note": "在機場品嚐的炸物丼。",
    "rating": 3.1,
    "tags": [
      "donburi",
      "airport"
    ],
    "images": [
      "images/food/機場丼飯/1.jpeg",
      "images/food/機場丼飯/2.jpeg"
    ],
    "mapUrl": ""
  },
  {
    "id": "susukino-crab-buffet",
    "title": "螃蟹吃到飽（ススキノ）",
    "note": "以帝王蟹為主的吃到飽餐廳，位於薄野商圈。",
    "rating": 4.2,
    "tags": [
      "buffet",
      "crab",
      "seafood",
      "susukino"
    ],
    "images": [
      "images/food/螃蟹吃到飽/1.jpeg",
      "images/food/螃蟹吃到飽/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/GVBTGtLYq1ZDRABA8"
  },
  {
    "id": "menya-kaiko-new-chitose",
    "title": "麺屋 開高",
    "note": "機場內的拉麵店，拉麵本身普通。",
    "rating": 3.2,
    "tags": [
      "ramen",
      "airport"
    ],
    "images": [
      "images/food/麺屋 開高 新千歳空港店/IMG_2804.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/VR3Vc8Ena6Qt31Ae8"
  },
  {
    "id": "letao-ice-cookie",
    "title": "LeTAO 冰淇淋餅乾",
    "note": "小樽名店 LeTAO 的甜點系列。",
    "rating": 4.5,
    "tags": [
      "dessert",
      "ice-cream",
      "cookie"
    ],
    "images": [
      "images/food/LeTAO冰淇淋餅乾/1.jpeg",
      "images/food/LeTAO冰淇淋餅乾/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/8sWxgtEUaaPTAVVf8"
  },
  {
    "id": "menya-unga-ramen",
    "title": "Menya Unga 牛腸拉麵",
    "note": "特色牛腸拉麵，湯頭濃郁。",
    "rating": 4.3,
    "tags": [
      "ramen",
      "offal"
    ],
    "images": [
      "images/food/Menya Unga 牛腸拉麵/IMG_3098.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/nfLEtFNXr3rBGQPU6"
  },
  {
    "id": "otaru-crown-ramen",
    "title": "Otaru Crown 扇貝拉麵",
    "note": "扇貝鮮味湯頭的拉麵。",
    "rating": 4.2,
    "tags": [
      "ramen",
      "seafood"
    ],
    "images": [
      "images/food/Otaru Crown 扇貝拉麵/IMG_3003.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/Q6FpYQAPAe5st33GA"
  },
  {
    "id": "toya-curry",
    "title": "The Toya Curry",
    "note": "洞爺湖當地的咖哩專門店。",
    "rating": 4.3,
    "tags": [
      "curry",
      "local"
    ],
    "images": [
      "images/food/The Toya curry/1.jpeg",
      "images/food/The Toya curry/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/PhHyxWhUN1fiCUhk7"
  },
  {
    "id": "ishimame-soba",
    "title": "いし豆 蕎麥麵",
    "note": "特色蕎麥麵，口感扎實，每日限量。",
    "rating": 4.7,
    "tags": [
      "soba",
      "noodles"
    ],
    "images": [
      "images/food/Ishimame Soba/1.jpeg",
      "images/food/Ishimame Soba/2.jpeg",
      "images/food/Ishimame Soba/3.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/oK44Qjn1hEA9HY3p6"
  },
  {
    "id": "takahashi-farm",
    "title": "ニセコ 高橋牧場",
    "note": "以乳製品與甜點聞名的牧場。",
    "rating": 4,
    "tags": [
      "farm",
      "dessert",
      "milk"
    ],
    "images": [
      "images/food/高橋牧場/1.jpeg",
      "images/food/高橋牧場/2.jpeg"
    ],
    "mapUrl": "https://maps.app.goo.gl/c66AcQZGDBgEVnCW6"
  }
];

export const galleryImages = [
  "images/gallery/1.jpeg",
  "images/gallery/2.jpeg",
  "images/gallery/3.jpeg",
  "images/gallery/4.jpeg"
];
export const friendsPhotos = [
  "images/friends/1.jpg",
  "images/friends/2.jpg",
  "images/friends/3.jpeg"
];
